import { FormValues } from "./formTypes";

export const initialValues: FormValues = {
  subProjectId: "",
  customerName: "",
  mobileNo: "",
  connectionStatus: "",
  aadharNo: "",
  connectionUse: "",
  plotFlatNo: "",
  buildingName: "",
  areaName: "",
  nearLandmark: "",
  pinCodeNo: "",
  meterMake: "",
  meterSerialNo: "",
  remark: "",
  email: "",
  consumerNumber: "",
  meterInterfaceUnitNo: "",
  blockNo: "",
  wardOffice: "",
  companyName: "",
  grampanchyat: "",
  noOfFamily: "",
  noOfFamilyNumber: "",
  totalFlats: "",
  gisPlotId: "",
  installationPhotos: undefined,
  customerSignature: undefined,
  agentSignature: undefined,
};
